export const REGISTR_USER_REQUEST: 'REGISTR_USER_REQUEST' = 'REGISTR_USER_REQUEST';
export const REGISTR_USER_SUCCESS: 'REGISTR_USER_SUCCESS' = 'REGISTR_USER_SUCCESS';
export const REGISTR_USER_FAILED: 'REGISTR_USER_FAILED' = 'REGISTR_USER_FAILED';
export const RESET_REGISTER_ERR: 'RESET_REGISTER_ERR' = 'RESET_REGISTER_ERR';

export const PWD_RECOVER_REQUEST: 'PWD_RECOVER_REQUEST' = 'PWD_RECOVER_REQUEST';
export const PWD_RECOVER_FAILED: 'PWD_RECOVER_FAILED' = 'PWD_RECOVER_FAILED';
export const PWD_RECOVER_SUCCESS: 'PWD_RECOVER_SUCCESS' = 'PWD_RECOVER_SUCCESS';
export const RESET_PWD_RECOVER_ERR: 'RESET_RECOVER_ERR' = 'RESET_RECOVER_ERR';

export const LOG_IN_REQUEST: 'LOG_IN_REQUEST' = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS: 'LOG_IN_SUCCESS' = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILED: 'LOG_IN_FAILED' = 'LOG_IN_FAILED';
export const RESET_LOG_IN_ERR: 'RESET_LOG_IN_ERR' = 'RESET_LOG_IN_ERR';

export const LOG_OUT_REQUEST: 'LOG_OUT_REQUEST' = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS' = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILED: 'LOG_OUT_FAILED' = 'LOG_OUT_FAILED';
export const RESET_LOG_OUT_ERR: 'RESET_LOG_OUT_ERR' = 'RESET_LOG_OUT_ERR';

export const PWD_RESET_REQUEST: 'PWD_RESET_REQUEST' = 'PWD_RESET_REQUEST';
export const PWD_RESET_SUCCESS: 'PWD_RESET_SUCCESS' = 'PWD_RESET_SUCCESS';
export const PWD_RESET_FAILED: 'PWD_RESET_FAILED' = 'PWD_RESET_FAILED';
export const RESET_PWD_RESET_ERR: 'RESET_PWD_RESET_ERR' = 'RESET_PWD_RESET_ERR';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';
export const RESET_GET_USER_ERR: 'RESET_GET_USER_ERR' = 'RESET_GET_USER_ERR';

export const PATCH_USER_REQUEST: 'PATCH_USER_REQUEST' = 'PATCH_USER_REQUEST';
export const PATCH_USER_SUCCESS: 'PATCH_USER_SUCCESS' = 'PATCH_USER_SUCCESS';
export const PATCH_USER_FAILED: 'PATCH_USER_FAILED' = 'PATCH_USER_FAILED';
export const RESET_PATCH_USER_ERR: 'RESET_PATCH_USER_ERR' = 'RESET_PATCH_USER_ERR';

export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED' = 'REFRESH_TOKEN_FAILED';
export const RESET_REFRESH_TOKEN_ERR: 'RESET_REFRESH_TOKEN_ERR' = 'RESET_REFRESH_TOKEN_ERR';

export const CHECK_AUTH: 'CHECK_AUTH' = 'CHECK_AUTH';
export const CHECK_AUTH_CHECKED: 'CHECK_AUTH_CHECKED' = 'CHECK_AUTH_CHECKED';
